#!/bin/sh
. "$(dirname "$0")/_/husky.sh"

if yarn git-branch-is develop 
then
yarn version --no-git-tag-version --no-commit-hooks --minor
elif yarn git-branch-is master
then
yarn version --no-git-tag-version --no-commit-hooks --major
else
yarn version --no-git-tag-version --no-commit-hooks --patch
fi

git add .