name: Automated Deploy

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/cache@v2
        with:
          key: ${{runner.os}}-modules-${{hashFiles('**/yarn.lock')}}
          path: '**/node_modules'

      - name: Setup Node.js environment
        uses: actions/setup-node@v2.1.4
        with:
          node-version: '12.x'        
      
      - name: Install Dependencies
        run: yarn
   
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2.1.4
      - name: Deploy
        env:
          NODE_AUTH_TOKEN: ${{ secrets.GH_TOKEN }}
        run: |
          git remote rm origin
          git remote add origin https://github.com/$GITHUB_REPOSITORY.git
          yarn ng add angular-cli-ghpages
          yarn ng deploy --cname=${{ secrets.PAGE_URL }} --name=${{ secrets.USERNAME }} --email=${{ secrets.EMAIL }}
        
      
